---
- name: Install zsh
  package:
    name: zsh
    state: present

- name: copy .zshrc
  copy:
    src: templates/zshrc.j2
    dest: /root/.zshrc
    owner: root
    group: root
    mode: '0600'
    backup: yes

- name: set zsh default
  user:
    name: root
    shell: /usr/bin/zsh